# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from oxford_dictionaries_api.models.lemmatron_lexical_entry import LemmatronLexicalEntry  # noqa: F401,E501


class HeadwordLemmatron(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'language': 'str',
        'lexical_entries': 'list[LemmatronLexicalEntry]',
        'type': 'str',
        'word': 'str'
    }

    attribute_map = {
        'id': 'id',
        'language': 'language',
        'lexical_entries': 'lexicalEntries',
        'type': 'type',
        'word': 'word'
    }

    def __init__(self, id=None, language=None, lexical_entries=None, type=None, word=None):  # noqa: E501
        """HeadwordLemmatron - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._language = None
        self._lexical_entries = None
        self._type = None
        self._word = None
        self.discriminator = None

        self.id = id
        self.language = language
        self.lexical_entries = lexical_entries
        if type is not None:
            self.type = type
        self.word = word

    @property
    def id(self):
        """Gets the id of this HeadwordLemmatron.  # noqa: E501

        The identifier of a word  # noqa: E501

        :return: The id of this HeadwordLemmatron.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HeadwordLemmatron.

        The identifier of a word  # noqa: E501

        :param id: The id of this HeadwordLemmatron.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def language(self):
        """Gets the language of this HeadwordLemmatron.  # noqa: E501

        IANA language code  # noqa: E501

        :return: The language of this HeadwordLemmatron.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this HeadwordLemmatron.

        IANA language code  # noqa: E501

        :param language: The language of this HeadwordLemmatron.  # noqa: E501
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")  # noqa: E501

        self._language = language

    @property
    def lexical_entries(self):
        """Gets the lexical_entries of this HeadwordLemmatron.  # noqa: E501

        A grouping of various senses in a specific language, and a lexical category that relates to a word  # noqa: E501

        :return: The lexical_entries of this HeadwordLemmatron.  # noqa: E501
        :rtype: list[LemmatronLexicalEntry]
        """
        return self._lexical_entries

    @lexical_entries.setter
    def lexical_entries(self, lexical_entries):
        """Sets the lexical_entries of this HeadwordLemmatron.

        A grouping of various senses in a specific language, and a lexical category that relates to a word  # noqa: E501

        :param lexical_entries: The lexical_entries of this HeadwordLemmatron.  # noqa: E501
        :type: list[LemmatronLexicalEntry]
        """
        if lexical_entries is None:
            raise ValueError("Invalid value for `lexical_entries`, must not be `None`")  # noqa: E501

        self._lexical_entries = lexical_entries

    @property
    def type(self):
        """Gets the type of this HeadwordLemmatron.  # noqa: E501

        The json object type. Could be 'headword', 'inflection' or 'phrase'  # noqa: E501

        :return: The type of this HeadwordLemmatron.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this HeadwordLemmatron.

        The json object type. Could be 'headword', 'inflection' or 'phrase'  # noqa: E501

        :param type: The type of this HeadwordLemmatron.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def word(self):
        """Gets the word of this HeadwordLemmatron.  # noqa: E501

        A given written or spoken realisation of a an entry, lowercased.  # noqa: E501

        :return: The word of this HeadwordLemmatron.  # noqa: E501
        :rtype: str
        """
        return self._word

    @word.setter
    def word(self, word):
        """Sets the word of this HeadwordLemmatron.

        A given written or spoken realisation of a an entry, lowercased.  # noqa: E501

        :param word: The word of this HeadwordLemmatron.  # noqa: E501
        :type: str
        """
        if word is None:
            raise ValueError("Invalid value for `word`, must not be `None`")  # noqa: E501

        self._word = word

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HeadwordLemmatron):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
