# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from oxford_dictionaries_api.models.thesaurus_entry import ThesaurusEntry  # noqa: F401,E501
from oxford_dictionaries_api.models.variant_forms_list import VariantFormsList  # noqa: F401,E501


class ThesaurusLexicalEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entries': 'list[ThesaurusEntry]',
        'language': 'str',
        'lexical_category': 'str',
        'text': 'str',
        'variant_forms': 'VariantFormsList'
    }

    attribute_map = {
        'entries': 'entries',
        'language': 'language',
        'lexical_category': 'lexicalCategory',
        'text': 'text',
        'variant_forms': 'variantForms'
    }

    def __init__(self, entries=None, language=None, lexical_category=None, text=None, variant_forms=None):  # noqa: E501
        """ThesaurusLexicalEntry - a model defined in Swagger"""  # noqa: E501

        self._entries = None
        self._language = None
        self._lexical_category = None
        self._text = None
        self._variant_forms = None
        self.discriminator = None

        if entries is not None:
            self.entries = entries
        self.language = language
        self.lexical_category = lexical_category
        self.text = text
        if variant_forms is not None:
            self.variant_forms = variant_forms

    @property
    def entries(self):
        """Gets the entries of this ThesaurusLexicalEntry.  # noqa: E501


        :return: The entries of this ThesaurusLexicalEntry.  # noqa: E501
        :rtype: list[ThesaurusEntry]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this ThesaurusLexicalEntry.


        :param entries: The entries of this ThesaurusLexicalEntry.  # noqa: E501
        :type: list[ThesaurusEntry]
        """

        self._entries = entries

    @property
    def language(self):
        """Gets the language of this ThesaurusLexicalEntry.  # noqa: E501

        IANA language code  # noqa: E501

        :return: The language of this ThesaurusLexicalEntry.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this ThesaurusLexicalEntry.

        IANA language code  # noqa: E501

        :param language: The language of this ThesaurusLexicalEntry.  # noqa: E501
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")  # noqa: E501

        self._language = language

    @property
    def lexical_category(self):
        """Gets the lexical_category of this ThesaurusLexicalEntry.  # noqa: E501

        A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb  # noqa: E501

        :return: The lexical_category of this ThesaurusLexicalEntry.  # noqa: E501
        :rtype: str
        """
        return self._lexical_category

    @lexical_category.setter
    def lexical_category(self, lexical_category):
        """Sets the lexical_category of this ThesaurusLexicalEntry.

        A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb  # noqa: E501

        :param lexical_category: The lexical_category of this ThesaurusLexicalEntry.  # noqa: E501
        :type: str
        """
        if lexical_category is None:
            raise ValueError("Invalid value for `lexical_category`, must not be `None`")  # noqa: E501

        self._lexical_category = lexical_category

    @property
    def text(self):
        """Gets the text of this ThesaurusLexicalEntry.  # noqa: E501

        A given written or spoken realisation of a an entry.  # noqa: E501

        :return: The text of this ThesaurusLexicalEntry.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ThesaurusLexicalEntry.

        A given written or spoken realisation of a an entry.  # noqa: E501

        :param text: The text of this ThesaurusLexicalEntry.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def variant_forms(self):
        """Gets the variant_forms of this ThesaurusLexicalEntry.  # noqa: E501

        Various words that are used interchangeably depending on the context, e.g 'a' and 'an'  # noqa: E501

        :return: The variant_forms of this ThesaurusLexicalEntry.  # noqa: E501
        :rtype: VariantFormsList
        """
        return self._variant_forms

    @variant_forms.setter
    def variant_forms(self, variant_forms):
        """Sets the variant_forms of this ThesaurusLexicalEntry.

        Various words that are used interchangeably depending on the context, e.g 'a' and 'an'  # noqa: E501

        :param variant_forms: The variant_forms of this ThesaurusLexicalEntry.  # noqa: E501
        :type: VariantFormsList
        """

        self._variant_forms = variant_forms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThesaurusLexicalEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
