# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from oxford_dictionaries_api.models.arrayofstrings import Arrayofstrings  # noqa: F401,E501


class VariantFormsListInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'regions': 'Arrayofstrings',
        'text': 'str'
    }

    attribute_map = {
        'regions': 'regions',
        'text': 'text'
    }

    def __init__(self, regions=None, text=None):  # noqa: E501
        """VariantFormsListInner - a model defined in Swagger"""  # noqa: E501

        self._regions = None
        self._text = None
        self.discriminator = None

        if regions is not None:
            self.regions = regions
        self.text = text

    @property
    def regions(self):
        """Gets the regions of this VariantFormsListInner.  # noqa: E501

        A particular area in which the variant form occurs, e.g. 'Great Britain'  # noqa: E501

        :return: The regions of this VariantFormsListInner.  # noqa: E501
        :rtype: Arrayofstrings
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this VariantFormsListInner.

        A particular area in which the variant form occurs, e.g. 'Great Britain'  # noqa: E501

        :param regions: The regions of this VariantFormsListInner.  # noqa: E501
        :type: Arrayofstrings
        """

        self._regions = regions

    @property
    def text(self):
        """Gets the text of this VariantFormsListInner.  # noqa: E501


        :return: The text of this VariantFormsListInner.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this VariantFormsListInner.


        :param text: The text of this VariantFormsListInner.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VariantFormsListInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
