# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.models.grammatical_features_list_inner import GrammaticalFeaturesListInner  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestGrammaticalFeaturesListInner(unittest.TestCase):
    """GrammaticalFeaturesListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrammaticalFeaturesListInner(self):
        """Test GrammaticalFeaturesListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = oxford_dictionaries_api.models.grammatical_features_list_inner.GrammaticalFeaturesListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
