# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.api.wordlist_api import WordlistApi  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestWordlistApi(unittest.TestCase):
    """WordlistApi unit test stubs"""

    def setUp(self):
        self.api = oxford_dictionaries_api.api.wordlist_api.WordlistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_wordlist_source_lang_filters_advanced_get(self):
        """Test case for wordlist_source_lang_filters_advanced_get

        Retrieve list of words for category with advanced options  # noqa: E501
        """
        pass

    def test_wordlist_source_lang_filters_basic_get(self):
        """Test case for wordlist_source_lang_filters_basic_get

        Retrieve a list of words in a category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
