# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.api.lemmatron_api import LemmatronApi  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestLemmatronApi(unittest.TestCase):
    """LemmatronApi unit test stubs"""

    def setUp(self):
        self.api = oxford_dictionaries_api.api.lemmatron_api.LemmatronApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inflections_source_lang_word_id_filters_get(self):
        """Test case for inflections_source_lang_word_id_filters_get

        Apply optional filters to Lemmatron response  # noqa: E501
        """
        pass

    def test_inflections_source_lang_word_id_get(self):
        """Test case for inflections_source_lang_word_id_get

        Check a word exists in the dictionary and retrieve its root form  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
