# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.api.thesaurus_api import ThesaurusApi  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestThesaurusApi(unittest.TestCase):
    """ThesaurusApi unit test stubs"""

    def setUp(self):
        self.api = oxford_dictionaries_api.api.thesaurus_api.ThesaurusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entries_source_lang_word_id_antonyms_get(self):
        """Test case for entries_source_lang_word_id_antonyms_get

        Retrieve words that mean the opposite  # noqa: E501
        """
        pass

    def test_entries_source_lang_word_id_synonyms_get(self):
        """Test case for entries_source_lang_word_id_synonyms_get

        Retrieve words that are similar  # noqa: E501
        """
        pass

    def test_entries_source_lang_word_id_synonymsantonyms_get(self):
        """Test case for entries_source_lang_word_id_synonymsantonyms_get

        Retrieve synonyms and antonyms for a given word  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
