# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.api.search_api import SearchApi  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = oxford_dictionaries_api.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_source_lang_get(self):
        """Test case for search_source_lang_get

        Retrieve possible matches to input  # noqa: E501
        """
        pass

    def test_search_source_search_language_translationstarget_search_language_get(self):
        """Test case for search_source_search_language_translationstarget_search_language_get

        Retrieve possible translation matches to input  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
