# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.api.lexi_stats_api import LexiStatsApi  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestLexiStatsApi(unittest.TestCase):
    """LexiStatsApi unit test stubs"""

    def setUp(self):
        self.api = oxford_dictionaries_api.api.lexi_stats_api.LexiStatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stats_frequency_ngrams_source_lang_corpus_ngram_size_get(self):
        """Test case for stats_frequency_ngrams_source_lang_corpus_ngram_size_get

        Retrieve the frequency of ngrams (1-4) derived from a corpus  # noqa: E501
        """
        pass

    def test_stats_frequency_word_source_lang_get(self):
        """Test case for stats_frequency_word_source_lang_get

        Retrieve the frequency of a word derived from a corpus.  # noqa: E501
        """
        pass

    def test_stats_frequency_words_source_lang_get(self):
        """Test case for stats_frequency_words_source_lang_get

        Retrieve a list of frequencies of a word/words derived from a corpus.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
