# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.api.dictionary_entries_api import DictionaryEntriesApi  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestDictionaryEntriesApi(unittest.TestCase):
    """DictionaryEntriesApi unit test stubs"""

    def setUp(self):
        self.api = oxford_dictionaries_api.api.dictionary_entries_api.DictionaryEntriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entries_source_lang_word_id_filters_get(self):
        """Test case for entries_source_lang_word_id_filters_get

        Apply filters to response  # noqa: E501
        """
        pass

    def test_entries_source_lang_word_id_get(self):
        """Test case for entries_source_lang_word_id_get

        Retrieve dictionary information for a given word  # noqa: E501
        """
        pass

    def test_entries_source_lang_word_id_regionsregion_get(self):
        """Test case for entries_source_lang_word_id_regionsregion_get

        Specify GB or US dictionary for English entry search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
