# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oxford_dictionaries_api
from oxford_dictionaries_api.models.languages_target_language import LanguagesTargetLanguage  # noqa: E501
from oxford_dictionaries_api.rest import ApiException


class TestLanguagesTargetLanguage(unittest.TestCase):
    """LanguagesTargetLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguagesTargetLanguage(self):
        """Test LanguagesTargetLanguage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = oxford_dictionaries_api.models.languages_target_language.LanguagesTargetLanguage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
