# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from oxford_dictionaries_api.api_client import ApiClient


class TranslationApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def entries_source_translation_language_word_id_translationstarget_translation_language_get(self, source_translation_language, word_id, target_translation_language, app_id, app_key, **kwargs):  # noqa: E501
        """Retrieve translation for a given word  # noqa: E501

         Use this to return translations for a given word. In the event that a word in the dataset does not have a direct translation, the response will be a [definition](documentation/glossary?term=entry) in the target language.    <div id=\"translation\"></div>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.entries_source_translation_language_word_id_translationstarget_translation_language_get(source_translation_language, word_id, target_translation_language, app_id, app_key, async=True)
        >>> result = thread.get()

        :param async bool
        :param str source_translation_language: IANA language code (required)
        :param str word_id: The source word (required)
        :param str target_translation_language: IANA language code (required)
        :param str app_id: App ID Authentication Parameter (required)
        :param str app_key: App Key Authentication Parameter (required)
        :return: RetrieveEntry
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.entries_source_translation_language_word_id_translationstarget_translation_language_get_with_http_info(source_translation_language, word_id, target_translation_language, app_id, app_key, **kwargs)  # noqa: E501
        else:
            (data) = self.entries_source_translation_language_word_id_translationstarget_translation_language_get_with_http_info(source_translation_language, word_id, target_translation_language, app_id, app_key, **kwargs)  # noqa: E501
            return data

    def entries_source_translation_language_word_id_translationstarget_translation_language_get_with_http_info(self, source_translation_language, word_id, target_translation_language, app_id, app_key, **kwargs):  # noqa: E501
        """Retrieve translation for a given word  # noqa: E501

         Use this to return translations for a given word. In the event that a word in the dataset does not have a direct translation, the response will be a [definition](documentation/glossary?term=entry) in the target language.    <div id=\"translation\"></div>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.entries_source_translation_language_word_id_translationstarget_translation_language_get_with_http_info(source_translation_language, word_id, target_translation_language, app_id, app_key, async=True)
        >>> result = thread.get()

        :param async bool
        :param str source_translation_language: IANA language code (required)
        :param str word_id: The source word (required)
        :param str target_translation_language: IANA language code (required)
        :param str app_id: App ID Authentication Parameter (required)
        :param str app_key: App Key Authentication Parameter (required)
        :return: RetrieveEntry
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_translation_language', 'word_id', 'target_translation_language', 'app_id', 'app_key']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method entries_source_translation_language_word_id_translationstarget_translation_language_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_translation_language' is set
        if ('source_translation_language' not in params or
                params['source_translation_language'] is None):
            raise ValueError("Missing the required parameter `source_translation_language` when calling `entries_source_translation_language_word_id_translationstarget_translation_language_get`")  # noqa: E501
        # verify the required parameter 'word_id' is set
        if ('word_id' not in params or
                params['word_id'] is None):
            raise ValueError("Missing the required parameter `word_id` when calling `entries_source_translation_language_word_id_translationstarget_translation_language_get`")  # noqa: E501
        # verify the required parameter 'target_translation_language' is set
        if ('target_translation_language' not in params or
                params['target_translation_language'] is None):
            raise ValueError("Missing the required parameter `target_translation_language` when calling `entries_source_translation_language_word_id_translationstarget_translation_language_get`")  # noqa: E501
        # verify the required parameter 'app_id' is set
        if ('app_id' not in params or
                params['app_id'] is None):
            raise ValueError("Missing the required parameter `app_id` when calling `entries_source_translation_language_word_id_translationstarget_translation_language_get`")  # noqa: E501
        # verify the required parameter 'app_key' is set
        if ('app_key' not in params or
                params['app_key'] is None):
            raise ValueError("Missing the required parameter `app_key` when calling `entries_source_translation_language_word_id_translationstarget_translation_language_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'source_translation_language' in params:
            path_params['source_translation_language'] = params['source_translation_language']  # noqa: E501
        if 'word_id' in params:
            path_params['word_id'] = params['word_id']  # noqa: E501
        if 'target_translation_language' in params:
            path_params['target_translation_language'] = params['target_translation_language']  # noqa: E501

        query_params = []

        header_params = {}
        if 'app_id' in params:
            header_params['app_id'] = params['app_id']  # noqa: E501
        if 'app_key' in params:
            header_params['app_key'] = params['app_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/entries/{source_translation_language}/{word_id}/translations={target_translation_language}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RetrieveEntry',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
